import { Place, ItineraryDay, TripNote, TripExpense, Trip, SPTransportLine } from '../types';

export const INITIAL_TRIP: Trip = {
  id: 'trip-sp-2026',
  title: 'Explorando São Paulo 🏙️',
  description: 'Nossa viagem incrível por Sampa: cultura na Paulista, gastronomia na Liberdade, arte na Vila Madalena e parques!',
  startDate: '2026-10-15',
  endDate: '2026-10-19',
  coverImage: 'https://images.unsplash.com/photo-1578059425556-9e900f074a3f?auto=format&fit=crop&w=1600&q=80',
  participants: ['Lucas', 'Mariana', 'Pedro', 'Camila'],
  currentUser: 'Lucas',
};

export const SP_METRO_LINES: SPTransportLine[] = [
  {
    id: 'l1',
    name: 'Linha 1 - Azul',
    type: 'metro',
    color: 'Azul',
    hexColor: '#00539B',
    stationsCount: 23,
    highlights: ['Liberdade', 'Sé', 'São Bento (25 de Março)', 'Tiradentes (Pinacoteca)', 'Luz'],
  },
  {
    id: 'l2',
    name: 'Linha 2 - Verde',
    type: 'metro',
    color: 'Verde',
    hexColor: '#008060',
    stationsCount: 14,
    highlights: ['Brigadeiro (Japan House/Sesc)', 'Trianon-MASP', 'Consolação (Paulista)', 'Vila Madalena'],
  },
  {
    id: 'l3',
    name: 'Linha 3 - Vermelha',
    type: 'metro',
    color: 'Vermelha',
    hexColor: '#EE3124',
    stationsCount: 18,
    highlights: ['Anhangabaú (Theatro Municipal)', 'Sé', 'República', 'Palmeiras-Barra Funda'],
  },
  {
    id: 'l4',
    name: 'Linha 4 - Amarela',
    type: 'viaquatro',
    color: 'Amarela',
    hexColor: '#FFF000',
    stationsCount: 11,
    highlights: ['Paulista', 'Oscar Freire (Jardins)', 'Fradique Coutinho (Pinheiros)', 'Faria Lima', 'República', 'Luz'],
  },
  {
    id: 'l5',
    name: 'Linha 5 - Lilás',
    type: 'viamobilidade',
    color: 'Lilás',
    hexColor: '#9B388D',
    stationsCount: 17,
    highlights: ['AACD-Servidor (Parque Ibirapuera)', 'Moema', 'Santa Cruz'],
  },
  {
    id: 'l9',
    name: 'Linha 9 - Esmeralda (CPTM/ViaMobilidade)',
    type: 'viamobilidade',
    color: 'Esmeralda',
    hexColor: '#00A88F',
    stationsCount: 20,
    highlights: ['Villa-Lobos Jaguaré (Parque Villa-Lobos)', 'Pinheiros', 'Berrini (Ponte Estaiada)', 'Morumbi'],
  },
];

export const INITIAL_PLACES: Place[] = [
  {
    id: 'p-masp',
    name: 'MASP (Museu de Arte de São Paulo)',
    category: 'cultura',
    neighborhood: 'Bela Vista / Av. Paulista',
    address: 'Av. Paulista, 1578 - Bela Vista',
    lat: -23.561494,
    lng: -46.655881,
    description: 'Um dos maiores museus de arte da América Latina com o icônico vão livre projetado por Lina Bo Bardi e cavaletes de cristal.',
    priceLevel: 2,
    rating: 4.8,
    estimatedTimeMins: 120,
    photoUrl: 'https://images.unsplash.com/photo-1583275479278-858bf23700f2?auto=format&fit=crop&w=800&q=80',
    tags: ['Arte', 'Arquitetura', 'Imperdível', 'Av. Paulista', 'Terça-feira Grátis'],
    metroStation: 'Estação Trianon-MASP',
    metroLine: 'Linha 2-Verde',
    status: 'planned',
    createdBy: 'Lucas',
    createdAt: '2026-09-01T10:00:00Z',
    openingHours: 'Ter a Dom: 10h às 18h (Quinta até 20h)',
    votes: [
      { id: 'v1', placeId: 'p-masp', userName: 'Mariana', voteType: 'super_want', comment: 'Com certeza quero ver os cavaletes de cristal!' },
      { id: 'v2', placeId: 'p-masp', userName: 'Pedro', voteType: 'up' },
    ],
  },
  {
    id: 'p-japan-house',
    name: 'Japan House São Paulo',
    category: 'cultura',
    neighborhood: 'Bela Vista / Av. Paulista',
    address: 'Av. Paulista, 52 - Bela Vista',
    lat: -23.570778,
    lng: -46.643265,
    description: 'Centro cultural que une a tradição e o Japão contemporâneo com exposições imersivas, café artesanal e arquitetura com fachada de madeira hinoki de Kengo Kuma.',
    priceLevel: 1,
    rating: 4.7,
    estimatedTimeMins: 75,
    photoUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80',
    tags: ['Cultura Japonesa', 'Grátis', 'Design', 'Café Especial'],
    metroStation: 'Estação Brigadeiro',
    metroLine: 'Linha 2-Verde',
    status: 'planned',
    createdBy: 'Mariana',
    createdAt: '2026-09-02T11:00:00Z',
    openingHours: 'Ter a Sex: 10h às 18h | Sáb: 9h às 19h | Dom: 9h às 18h',
    votes: [
      { id: 'v3', placeId: 'p-japan-house', userName: 'Lucas', voteType: 'super_want', comment: 'Entrada gratuita e o café do andar de cima é sensacional!' },
      { id: 'v4', placeId: 'p-japan-house', userName: 'Camila', voteType: 'up' },
    ],
  },
  {
    id: 'p-sesc-paulista',
    name: 'Mirante do Sesc Avenida Paulista',
    category: 'ponto_turistico',
    neighborhood: 'Bela Vista / Av. Paulista',
    address: 'Av. Paulista, 119 - Bela Vista',
    lat: -23.570254,
    lng: -46.643891,
    description: 'Mirante no 17º andar com uma das vistas panorâmicas mais deslumbrantes de toda a extensão da Avenida Paulista. Café no terraço e exposições.',
    priceLevel: 1,
    rating: 4.9,
    estimatedTimeMins: 60,
    photoUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
    tags: ['Vista Panorâmica', 'Foto Instagramável', 'Grátis', 'Cafeteria'],
    metroStation: 'Estação Brigadeiro',
    metroLine: 'Linha 2-Verde',
    status: 'planned',
    createdBy: 'Pedro',
    createdAt: '2026-09-02T12:00:00Z',
    openingHours: 'Ter a Sáb: 10h às 21h30 | Dom: 10h às 18h30 (Agendar pelo App Credencial Sesc SP)',
    votes: [
      { id: 'v5', placeId: 'p-sesc-paulista', userName: 'Lucas', voteType: 'super_want' },
      { id: 'v6', placeId: 'p-sesc-paulista', userName: 'Mariana', voteType: 'up' },
    ],
  },
  {
    id: 'p-liberdade',
    name: 'Bairro da Liberdade & Feirinha de Domingo',
    category: 'gastronomia',
    neighborhood: 'Liberdade',
    address: 'Praça da Liberdade, s/n - Liberdade',
    lat: -23.555239,
    lng: -46.635832,
    description: 'O maior reduto da comunidade japonesa fora do Japão. Lanternas orientais pelas ruas, mercados com doces asiáticos, lojas de anime, lámen autêntico e a famosa feirinha gastronômica.',
    priceLevel: 2,
    rating: 4.6,
    estimatedTimeMins: 180,
    photoUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    tags: ['Street Food', 'Comida Japonesa', 'Compras', 'Feira', 'Cultura'],
    metroStation: 'Estação Japão-Liberdade',
    metroLine: 'Linha 1-Azul',
    status: 'planned',
    createdBy: 'Camila',
    createdAt: '2026-09-03T14:00:00Z',
    openingHours: 'Comércio aberto diariamente | Feirinha aos sábados e domingos das 9h às 18h',
    votes: [
      { id: 'v7', placeId: 'p-liberdade', userName: 'Lucas', voteType: 'super_want', comment: 'Precisamos comer Guioza frito, Takoyaki e provar os Bubble Teas!' },
      { id: 'v8', placeId: 'p-liberdade', userName: 'Mariana', voteType: 'super_want' },
      { id: 'v9', placeId: 'p-liberdade', userName: 'Pedro', voteType: 'up' },
    ],
  },
  {
    id: 'p-beco-batman',
    name: 'Beco do Batman (Vila Madalena)',
    category: 'cultura',
    neighborhood: 'Vila Madalena',
    address: 'R. Medeiros de Albuquerque, 82-154 - Jardim das Bandeiras',
    lat: -23.557088,
    lng: -46.686524,
    description: 'Galeria de arte a céu aberto com dezenas de murais e grafites impressionantes que se renovam constantemente. Rodeado de bares boêmios, galerias e lojinhas.',
    priceLevel: 1,
    rating: 4.7,
    estimatedTimeMins: 90,
    photoUrl: 'https://images.unsplash.com/photo-1561055657-b9e0bf0fa360?auto=format&fit=crop&w=800&q=80',
    tags: ['Street Art', 'Grafite', 'Fotos', 'Bares', 'Vila Madalena'],
    metroStation: 'Estação Fradique Coutinho ou Faria Lima',
    metroLine: 'Linha 4-Amarela',
    status: 'planned',
    createdBy: 'Pedro',
    createdAt: '2026-09-04T09:30:00Z',
    openingHours: 'Aberto 24h (Melhor visitação durante o dia com luz natural)',
    votes: [
      { id: 'v10', placeId: 'p-beco-batman', userName: 'Mariana', voteType: 'up' },
      { id: 'v11', placeId: 'p-beco-batman', userName: 'Camila', voteType: 'super_want' },
    ],
  },
  {
    id: 'p-ibirapuera',
    name: 'Parque Ibirapuera & Pavilhão Japonês',
    category: 'parque',
    neighborhood: 'Vila Mariana / Moema',
    address: 'Av. Pedro Álvares Cabral - Vila Mariana',
    lat: -23.587416,
    lng: -46.657634,
    description: 'O pulmão verde de São Paulo projetado por Oscar Niemeyer e Burle Marx. Possui lagos, pistas de bicicleta/corrida, Museu Afro Brasil, MAM, Planetário e o Pavilhão Japonês com carpas.',
    priceLevel: 1,
    rating: 4.9,
    estimatedTimeMins: 180,
    photoUrl: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?auto=format&fit=crop&w=800&q=80',
    tags: ['Natureza', 'Piquenique', 'Niemeyer', 'Bicicleta', 'Museu Afro'],
    metroStation: 'Estação AACD-Servidor ou Brigadeiro + Ônibus',
    metroLine: 'Linha 5-Lilás / Linha 2-Verde',
    status: 'planned',
    createdBy: 'Lucas',
    createdAt: '2026-09-04T15:00:00Z',
    openingHours: 'Seg a Dom: 5h às 23h',
    votes: [
      { id: 'v12', placeId: 'p-ibirapuera', userName: 'Pedro', voteType: 'super_want', comment: 'Alugar uma bike no portão 3 e dar a volta no lago!' },
      { id: 'v13', placeId: 'p-ibirapuera', userName: 'Lucas', voteType: 'up' },
    ],
  },
  {
    id: 'p-pinacoteca',
    name: 'Pinacoteca de São Paulo & Pina Contemporânea',
    category: 'cultura',
    neighborhood: 'Luz / Bom Retiro',
    address: 'Praça da Luz, 2 - Luz',
    lat: -23.534279,
    lng: -46.633887,
    description: 'O museu de artes visuais mais antigo de São Paulo, instalado em um monumental edifício de tijolos aparentes restaurado por Paulo Mendes da Rocha, ao lado do Parque da Luz.',
    priceLevel: 2,
    rating: 4.8,
    estimatedTimeMins: 120,
    photoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    tags: ['Arte Brasileira', 'Arquitetura', 'Histórico', 'Sábado Grátis'],
    metroStation: 'Estação da Luz ou Tiradentes',
    metroLine: 'Linha 1-Azul / Linha 4-Amarela',
    status: 'planned',
    createdBy: 'Mariana',
    createdAt: '2026-09-05T10:00:00Z',
    openingHours: 'Qua a Seg: 10h às 18h (Sábado gratuito)',
    votes: [
      { id: 'v14', placeId: 'p-pinacoteca', userName: 'Mariana', voteType: 'super_want' },
      { id: 'v15', placeId: 'p-pinacoteca', userName: 'Lucas', voteType: 'up' },
    ],
  },
  {
    id: 'p-farol-santander',
    name: 'Farol Santander (Antigo Banespa)',
    category: 'ponto_turistico',
    neighborhood: 'Centro Histórico',
    address: 'R. João Brícola, 24 - Centro Histórico',
    lat: -23.546369,
    lng: -46.634024,
    description: 'Arranha-céu histórico inspirado no Empire State de NY. Conta com mirante no 26º andar com vista em 360º de SP, pista de skate, exposições de arte imersiva e o Bar do Cofre.',
    priceLevel: 2,
    rating: 4.7,
    estimatedTimeMins: 90,
    photoUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
    tags: ['Mirante', 'História', 'Centro', 'Bar do Cofre', 'Arte Imersiva'],
    metroStation: 'Estação São Bento',
    metroLine: 'Linha 1-Azul',
    status: 'wishlist',
    createdBy: 'Pedro',
    createdAt: '2026-09-05T14:30:00Z',
    openingHours: 'Ter a Dom: 9h às 20h',
    votes: [
      { id: 'v16', placeId: 'p-farol-santander', userName: 'Pedro', voteType: 'super_want', comment: 'Tomar um drink no Bar do Cofre no subsolo depois do mirante!' },
    ],
  },
  {
    id: 'p-bixiga-cantina',
    name: 'Cantina Roperto & Bixiga Tradicional',
    category: 'gastronomia',
    neighborhood: 'Bela Vista / Bixiga',
    address: 'R. Treze de Maio, 634 - Bela Vista',
    lat: -23.557436,
    lng: -46.645521,
    description: 'Bairro tradicional italiano famoso por suas cantinas com massas caseiras, pão italiano quentinho, antepastos fartos e ambiente acolhedor.',
    priceLevel: 3,
    rating: 4.6,
    estimatedTimeMins: 110,
    photoUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    tags: ['Massa Italiana', 'Tradição', 'Bixiga', 'Jantar em Grupo', 'Vinho'],
    metroStation: 'Estação São Joaquim ou Brigadeiro',
    metroLine: 'Linha 1-Azul / Linha 2-Verde',
    status: 'wishlist',
    createdBy: 'Lucas',
    createdAt: '2026-09-06T18:00:00Z',
    openingHours: 'Ter a Dom: 11h30 às 23h30',
    votes: [
      { id: 'v17', placeId: 'p-bixiga-cantina', userName: 'Camila', voteType: 'up', comment: 'Adoro nhoque e lasanha bolonhesa!' },
      { id: 'v18', placeId: 'p-bixiga-cantina', userName: 'Mariana', voteType: 'up' },
    ],
  },
  {
    id: 'p-mercadao',
    name: 'Mercado Municipal Paulistano (Mercadão)',
    category: 'gastronomia',
    neighborhood: 'Centro Histórico',
    address: 'R. Cantareira, 306 - Centro Histórico',
    lat: -23.541819,
    lng: -46.629471,
    description: 'Templo da gastronomia com vitrais deslumbrantes, frutas exóticas do mundo todo, o famoso sanduíche de mortadela e pastel gigante de bacalhau.',
    priceLevel: 2,
    rating: 4.4,
    estimatedTimeMins: 90,
    photoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    tags: ['Gastronomia', 'Sanduíche de Mortadela', 'Frutas', 'Histórico'],
    metroStation: 'Estação São Bento ou Luz',
    metroLine: 'Linha 1-Azul',
    status: 'wishlist',
    createdBy: 'Lucas',
    createdAt: '2026-09-06T19:00:00Z',
    openingHours: 'Seg a Sáb: 6h às 18h | Dom: 6h às 16h',
    votes: [
      { id: 'v19', placeId: 'p-mercadao', userName: 'Pedro', voteType: 'up' },
      { id: 'v20', placeId: 'p-mercadao', userName: 'Mariana', voteType: 'down', comment: 'Atenção aos vendedores de frutas insistentes. Melhor ir só pelo pastel.' },
    ],
  },
  {
    id: 'p-oscar-freire',
    name: 'Rua Oscar Freire & Cafés dos Jardins',
    category: 'compras',
    neighborhood: 'Jardins / Cerqueira César',
    address: 'Rua Oscar Freire, 800 - Cerqueira César',
    lat: -23.564561,
    lng: -46.669882,
    description: 'Rua arborizada e charmosa com lojas conceito, sorveterias artesanais (Bacio di Latte, Frida & Mina), cafeterias de grão especial e calçadas agradáveis para caminhar.',
    priceLevel: 3,
    rating: 4.7,
    estimatedTimeMins: 120,
    photoUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Passeio a Pé', 'Cafés', 'Sorvetes', 'Moda', 'Jardins'],
    metroStation: 'Estação Oscar Freire',
    metroLine: 'Linha 4-Amarela',
    status: 'wishlist',
    createdBy: 'Mariana',
    createdAt: '2026-09-07T10:00:00Z',
    openingHours: 'Comércio: 10h às 20h',
    votes: [
      { id: 'v21', placeId: 'p-oscar-freire', userName: 'Mariana', voteType: 'super_want' },
      { id: 'v22', placeId: 'p-oscar-freire', userName: 'Camila', voteType: 'super_want' },
    ],
  },
  {
    id: 'p-bar-vila-madalena',
    name: 'Bares da Rua Aspicuelta (Vila Madalena)',
    category: 'vida_noturna',
    neighborhood: 'Vila Madalena',
    address: 'R. Aspicuelta, 300 - Vila Madalena',
    lat: -23.555812,
    lng: -46.689812,
    description: 'O epicentro da vida noturna e boemia de SP. Bares com mesas na calçada, chopp estupidamente gelado, petiscos paulistanos (bolinho de feijoada, coxinha) e música ao vivo.',
    priceLevel: 2,
    rating: 4.7,
    estimatedTimeMins: 180,
    photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    tags: ['Vida Noturna', 'Chopp', 'Petiscos', 'Música ao Vivo', 'Boêmia'],
    metroStation: 'Estação Vila Madalena ou Fradique Coutinho',
    metroLine: 'Linha 2-Verde / Linha 4-Amarela',
    status: 'planned',
    createdBy: 'Pedro',
    createdAt: '2026-09-07T12:00:00Z',
    openingHours: 'Ter a Dom: 17h às 02h',
    votes: [
      { id: 'v23', placeId: 'p-bar-vila-madalena', userName: 'Lucas', voteType: 'super_want', comment: 'Perfeito para fechar o Dia 3 depois do Beco do Batman!' },
      { id: 'v24', placeId: 'p-bar-vila-madalena', userName: 'Pedro', voteType: 'super_want' },
    ],
  },
];

export const INITIAL_ITINERARY_DAYS: ItineraryDay[] = [
  {
    id: 'day-1',
    tripId: 'trip-sp-2026',
    dayNumber: 1,
    date: '2026-10-15',
    title: 'Dia 1: O Coração da Av. Paulista & Mirantes',
    description: 'Explorando os maiores cartões postais de São Paulo, museus internacionais e vista panorâmica no topo.',
    items: [
      {
        id: 'item-1',
        dayId: 'day-1',
        placeId: 'p-japan-house',
        orderIndex: 0,
        startTime: '10:00',
        endTime: '11:15',
        notes: 'Começar pelo início da Paulista (perto do Metrô Brigadeiro), ver a exposição e tomar um café.',
        transitMode: 'metro',
        transitDurationMins: 15,
        transitTips: 'Descer na Estação Brigadeiro (Linha 2-Verde), saída pela Rua Teixeira da Silva.',
      },
      {
        id: 'item-2',
        dayId: 'day-1',
        placeId: 'p-sesc-paulista',
        orderIndex: 1,
        startTime: '11:20',
        endTime: '12:30',
        notes: 'Subir ao Mirante do 17º andar para fotos deslumbrantes da Paulista inteira.',
        transitMode: 'walk',
        transitDurationMins: 3,
        transitTips: 'Caminhada de 1 minuto (fica logo em frente à Japan House).',
      },
      {
        id: 'item-3',
        dayId: 'day-1',
        placeId: 'p-masp',
        orderIndex: 2,
        startTime: '14:00',
        endTime: '16:30',
        notes: 'Almoço rápido na Paulista e depois visita ao acervo do MASP e vão livre.',
        transitMode: 'metro',
        transitDurationMins: 10,
        transitTips: 'Caminhada de 12 min pela Av. Paulista OU 1 estação de metrô (Brigadeiro -> Trianon-MASP).',
      },
      {
        id: 'item-4',
        dayId: 'day-1',
        placeId: 'p-bixiga-cantina',
        orderIndex: 3,
        startTime: '19:30',
        endTime: '22:00',
        notes: 'Jantar festivo de massas italianas no tradicional Bixiga.',
        transitMode: 'uber',
        transitDurationMins: 12,
        transitTips: 'Uber da Paulista até a R. Treze de Maio (cerca de R$ 14,00 a R$ 20,00).',
      },
    ],
  },
  {
    id: 'day-2',
    tripId: 'trip-sp-2026',
    dayNumber: 2,
    date: '2026-10-16',
    title: 'Dia 2: Cultura Oriental & Centro Histórico',
    description: 'Imersão no bairro da Liberdade, gastronomia asiática e arquitetura clássica da Pinacoteca.',
    items: [
      {
        id: 'item-5',
        dayId: 'day-2',
        placeId: 'p-liberdade',
        orderIndex: 0,
        startTime: '10:30',
        endTime: '13:30',
        notes: 'Comprar lembrancinhas, provar lanches orientais e almoçar lámen ou sushi.',
        transitMode: 'metro',
        transitDurationMins: 20,
        transitTips: 'Metrô Linha 1-Azul direto até Estação Japão-Liberdade.',
      },
      {
        id: 'item-6',
        dayId: 'day-2',
        placeId: 'p-pinacoteca',
        orderIndex: 1,
        startTime: '14:30',
        endTime: '17:00',
        notes: 'Passeio pela Pinacoteca e café no jardim do Parque da Luz.',
        transitMode: 'metro',
        transitDurationMins: 12,
        transitTips: 'Pegar Linha 1-Azul (Estação Liberdade -> Estação Luz), 4 paradas sem baldeação.',
      },
    ],
  },
  {
    id: 'day-3',
    tripId: 'trip-sp-2026',
    dayNumber: 3,
    date: '2026-10-17',
    title: 'Dia 3: Arte Urbana, Bares & Pôr do Sol',
    description: 'Caminhada artística pelo Beco do Batman, compras nos Jardins e chopp na boêmia Vila Madalena.',
    items: [
      {
        id: 'item-7',
        dayId: 'day-3',
        placeId: 'p-beco-batman',
        orderIndex: 0,
        startTime: '14:00',
        endTime: '16:00',
        notes: 'Sessão de fotos nos grafites mais coloridos da América Latina e galerias de arte.',
        transitMode: 'metro',
        transitDurationMins: 25,
        transitTips: 'Linha 4-Amarela até Fradique Coutinho + 10 min de caminhada ou Uber rápido.',
      },
      {
        id: 'item-8',
        dayId: 'day-3',
        placeId: 'p-bar-vila-madalena',
        orderIndex: 1,
        startTime: '17:30',
        endTime: '22:30',
        notes: 'Happy hour, porções de boteco e drinks com a galera para comemorar a viagem.',
        transitMode: 'walk',
        transitDurationMins: 6,
        transitTips: 'Caminhada de 5 minutos subindo a Rua Aspicuelta.',
      },
    ],
  },
  {
    id: 'day-4',
    tripId: 'trip-sp-2026',
    dayNumber: 4,
    date: '2026-10-18',
    title: 'Dia 4: Natureza no Ibirapuera & Jardins',
    description: 'Manhã relaxante ao ar livre no parque e tarde passeando pela elegante Oscar Freire.',
    items: [
      {
        id: 'item-9',
        dayId: 'day-4',
        placeId: 'p-ibirapuera',
        orderIndex: 0,
        startTime: '09:30',
        endTime: '13:00',
        notes: 'Aluguel de bike, caminhada pelo lago e visita ao Pavilhão Japonês.',
        transitMode: 'uber',
        transitDurationMins: 18,
        transitTips: 'Uber até o Portão 3 ou Metrô Linha 5-Lilás (Estação AACD-Servidor).',
      },
      {
        id: 'item-10',
        dayId: 'day-4',
        placeId: 'p-oscar-freire',
        orderIndex: 1,
        startTime: '15:00',
        endTime: '18:00',
        notes: 'Café da tarde, provar os melhores sorvetes e caminhar pelas lojas conceito.',
        transitMode: 'uber',
        transitDurationMins: 15,
        transitTips: 'Uber do Ibirapuera para a Oscar Freire (cerca de 12 min).',
      },
    ],
  },
];

export const INITIAL_NOTES: TripNote[] = [
  {
    id: 'note-1',
    tripId: 'trip-sp-2026',
    category: 'seguranca',
    title: '🛡️ Dicas de Segurança Importantes em SP',
    content: `1. **Celular na Rua**: Evite mexer no celular distraído na calçada, especialmente na Av. Paulista, Centro Histórico e Liberdade (atenção aos ciclistas/gangue da bike).
2. **Ao pedir Uber**: Entre em um estabelecimento ou portaria para pedir o carro, não fique na beira da rua com o celular na mão.
3. **Metrô**: É super seguro, limpo e rápido! Mantenha a mochila para a frente em horários de pico.
4. **Bolsas e Bolsos**: Mantenha carteira e celular em bolsos frontais com zíper.`,
    author: 'Mariana',
    isPinned: true,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'note-2',
    tripId: 'trip-sp-2026',
    category: 'transporte',
    title: '🚇 Como Funciona o Transporte em SP',
    content: `• **Metrô e CPTM**: Aceitam pagamento por aproximação (cartão de crédito/débito NFC e carteiras digitais no celular) direto na catraca em quase todas as estações ou através do aplicativo TOP.
• **Integração Gratuita**: Entre todas as linhas de metrô e CPTM nas estações de transferência (Luz, Sé, Paulista/Consolação, Paraíso, etc.).
• **Horários de Pico**: Evite pegar metrô das 7h às 9h e das 17h às 19h30 nas linhas Vermelha e Amarela se estiver com malas.
• **Táxi e Uber**: Funcionam 24h em qualquer bairro. Em dias de chuva, o trânsito nas marginais e avenidas principais costuma travar, prefira o Metrô nesses momentos!`,
    author: 'Lucas',
    isPinned: true,
    createdAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'note-3',
    tripId: 'trip-sp-2026',
    category: 'checklist',
    title: '🎒 O que Levar na Mochila de Passeio',
    content: 'Tênis confortável para andar muito em SP\nGuarda-chuva compacto ou capa (a famosa "terra da garoa")\nCarregador portátil (Powerbank)\nDocumento oficial com foto e carteirinha de estudante (para meia-entrada em museus como MASP e Pinacoteca)\nÓculos de sol e protetor solar',
    author: 'Camila',
    completed: false,
    createdAt: '2026-09-03T15:00:00Z',
  },
  {
    id: 'note-4',
    tripId: 'trip-sp-2026',
    category: 'dica_geral',
    title: '🍜 Gastronomia: Lugares Secretos para não perder',
    content: `• **Momo Lámen (Liberdade)**: Melhor caldo tonkotsu de SP.
• **Pastel da Maria**: Campeão do melhor pastel de feira de SP.
• **Pizzaria Bráz ou 1900**: Para provar a famosa pizza paulistana de massa artesanal.
• **A Baianeira (Masp)**: Comida brasileira afetiva deliciosa no subsolo do MASP.
• **Bar do Cofre SubAstor**: Fica dentro do cofre original do Banco do Estado de SP no Farol Santander.`,
    author: 'Pedro',
    createdAt: '2026-09-04T16:30:00Z',
  },
];

export const INITIAL_EXPENSES: TripExpense[] = [
  {
    id: 'exp-1',
    tripId: 'trip-sp-2026',
    title: 'Ingressos do MASP (4 pessoas)',
    amountCents: 24000, // R$ 240,00
    category: 'passeios',
    paidBy: 'Lucas',
    splitWith: ['Lucas', 'Mariana', 'Pedro', 'Camila'],
    date: '2026-10-15',
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'exp-2',
    tripId: 'trip-sp-2026',
    title: 'Almoço e lanches na Liberdade',
    amountCents: 28000, // R$ 280,00
    category: 'alimentacao',
    paidBy: 'Mariana',
    splitWith: ['Lucas', 'Mariana', 'Pedro', 'Camila'],
    date: '2026-10-16',
    createdAt: '2026-09-11T15:00:00Z',
  },
  {
    id: 'exp-3',
    tripId: 'trip-sp-2026',
    title: 'Uber do Aeroporto de Congonhas até Hotel',
    amountCents: 5200, // R$ 52,00
    category: 'transporte',
    paidBy: 'Pedro',
    splitWith: ['Lucas', 'Mariana', 'Pedro', 'Camila'],
    date: '2026-10-15',
    createdAt: '2026-09-10T09:00:00Z',
  },
];
